# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 305)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(100, 182, 62);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_frame = QtWidgets.QFrame(self.centralwidget)
        self.name_frame.setGeometry(QtCore.QRect(210, 10, 420, 150))
        self.name_frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.name_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.name_frame.setObjectName("name_frame")
        self.label = QtWidgets.QLabel(self.name_frame)
        self.label.setGeometry(QtCore.QRect(65, 10, 301, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.name_frame)
        self.label_2.setGeometry(QtCore.QRect(65, 45, 301, 20))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("text-align:center;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.name_frame)
        self.label_3.setGeometry(QtCore.QRect(65, 80, 301, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.name_frame)
        self.label_4.setGeometry(QtCore.QRect(65, 115, 301, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 200, 180, 70))
        self.pushButton.setStyleSheet("background-color: rgb(239, 255, 61);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 200, 180, 70))
        self.pushButton_2.setStyleSheet("background-color: rgb(239, 255, 61);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 200, 180, 70))
        self.pushButton_3.setStyleSheet("background-color: rgb(239, 255, 61);")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Головне вікно"))
        self.label.setText(_translate("MainWindow", "Грицюк Максим Юрійович"))
        self.label_2.setText(_translate("MainWindow", "ІО-02"))
        self.label_3.setText(_translate("MainWindow", "Номер у списку: 10"))
        self.label_4.setText(_translate("MainWindow", "Варіант : 14"))
        self.pushButton.setText(_translate("MainWindow", "Виклик вікна №2"))
        self.pushButton_2.setText(_translate("MainWindow", "Виклик вікна №4"))
        self.pushButton_3.setText(_translate("MainWindow", "Виклик вікна №3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
